(cl:defpackage semantic_knowledgebase-srv
  (:use )
  (:export
   "KBSERVICE"
   "<KBSERVICE-REQUEST>"
   "KBSERVICE-REQUEST"
   "<KBSERVICE-RESPONSE>"
   "KBSERVICE-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
  ))

