global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 10.0
  static_map: true
  inflation_radius: 1.0
  plugins: 
      - {name: static_layer,       type: "costmap_2d::StaticLayer"}
      - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
      - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
  #publish_frequency: 1.0
  footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]

