global_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   map_type: costmap
   update_frequency: 1.0
   publish_frequency: 1.0
   static_map: true
   transform_tolerance: 0.5
   plugins:
#        - {name: stactic_layer,     type: "costmap_2d::StaticLayer"}
#        - {name: stactic_layer,     type: "costmap_2d::StaticLayer"}
#        - {name: obstacles, type: "semantic_costmap::Obstacles"}
#        - {name: unknown_objects_layer, type: "semantic_costmap::UnknownObjectsLayer"}
#        - {name: structural_objects, type: "semantic_costmap::StructuralObjectsLayer"}
        - {name: heavy_objects, type: "semantic_costmap::HeavyObjectsLayer"}
        - {name: light_objects, type: "semantic_costmap::LightObjectsLayer"}
#        - {name: obstacles, type: "semantic_costmap::Obstacles"}
#        - {name: structural_layer, type: "semantic_costmap::StructuralLayer"} 
#        - {name: object_layer, type: "semantic_costmap::ObjectLayer"} 
#        - {name: structural_objects_layer, type: "semantic_costmap_layers::StructuralObjectsLayer"}        
#        - {name: inflation_structural_objects, type: "semantic_costmap_layers::InflationStructuralObjects"}
#        - {name: heavy_objects_layer, type: "semantic_costmap_layers::HeavyObjectsLayer"}
#        - {name: inflation_heavy_objects, type: "semantic_costmap_layers::InflationHeavyObjects"}
#        - {name: light_objects_layer, type: "semantic_costmap_layers::LightObjectsLayer"}
#        - {name: inflation_light_objects, type: "semantic_costmap_layers::InflationLightObjects"}


#        - {name: heavy_objects_layer, type: "semantic_costmap_layers::HeavyObjectsLayer"}
#        - {name: structural_objects_layer, type: "semantic_costmap_layers::StructuralObjectsLayer"}
#        - {name: inflation_structural_objects_layer, type: "semantic_costmap_layers::InflationStructuralObjects"}
#        - {name: heavy_objects_layer, type: "semantic_costmap_layers::HeavyObjectsLayer"}
#        - {name: structural_objects_layer, type: "semantic_costmap_layers::StructuralObjectsLayer"}
#        - {name: inflation_structural_objects_layer, type: "semantic_costmap_layers::InflationLayer"}
#        - {name: stactic_layer,     type: "costmap_2d::StaticLayer"}
#
#        - {name: obstacle_layer,     type: "costmap_2d::ObstacleLayer"}
#        - {name: inflation_layer,    type: "costmap_2d::InflationLayer"}
#   publish_frequency: 1.0
#   object_layer:
#       observation_sources: laser_scan_sensor
#       laser_scan_sensor: {data_type: LaserScan, sensor_frame: /lms100, clearing: true, marking: true, topic: /scan}


  
