"""autogenerated by genpy from p2os_msgs/GripState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GripState(genpy.Message):
  _md5sum = "370eb3507be0ed1043be50a3da3a07c6"
  _type = "p2os_msgs/GripState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# direction -1 is inward, +1 is outward, 0 is stationary
uint32 state
int32 dir
bool inner_beam
bool outer_beam
bool left_contact
bool right_contact

"""
  __slots__ = ['state','dir','inner_beam','outer_beam','left_contact','right_contact']
  _slot_types = ['uint32','int32','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       state,dir,inner_beam,outer_beam,left_contact,right_contact

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GripState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.state is None:
        self.state = 0
      if self.dir is None:
        self.dir = 0
      if self.inner_beam is None:
        self.inner_beam = False
      if self.outer_beam is None:
        self.outer_beam = False
      if self.left_contact is None:
        self.left_contact = False
      if self.right_contact is None:
        self.right_contact = False
    else:
      self.state = 0
      self.dir = 0
      self.inner_beam = False
      self.outer_beam = False
      self.left_contact = False
      self.right_contact = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_Ii4B.pack(_x.state, _x.dir, _x.inner_beam, _x.outer_beam, _x.left_contact, _x.right_contact))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.state, _x.dir, _x.inner_beam, _x.outer_beam, _x.left_contact, _x.right_contact,) = _struct_Ii4B.unpack(str[start:end])
      self.inner_beam = bool(self.inner_beam)
      self.outer_beam = bool(self.outer_beam)
      self.left_contact = bool(self.left_contact)
      self.right_contact = bool(self.right_contact)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_Ii4B.pack(_x.state, _x.dir, _x.inner_beam, _x.outer_beam, _x.left_contact, _x.right_contact))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.state, _x.dir, _x.inner_beam, _x.outer_beam, _x.left_contact, _x.right_contact,) = _struct_Ii4B.unpack(str[start:end])
      self.inner_beam = bool(self.inner_beam)
      self.outer_beam = bool(self.outer_beam)
      self.left_contact = bool(self.left_contact)
      self.right_contact = bool(self.right_contact)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_Ii4B = struct.Struct("<Ii4B")
