/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/brsu/catkin_ws/src/ensta_hbrs/semantic_knowledgebase/msg/GeometricProperties.msg
 *
 */


#ifndef SEMANTIC_KNOWLEDGEBASE_MESSAGE_GEOMETRICPROPERTIES_H
#define SEMANTIC_KNOWLEDGEBASE_MESSAGE_GEOMETRICPROPERTIES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <semantic_knowledgebase/BoundingBox.h>

namespace semantic_knowledgebase
{
template <class ContainerAllocator>
struct GeometricProperties_
{
  typedef GeometricProperties_<ContainerAllocator> Type;

  GeometricProperties_()
    : pose()
    , bounding_box()  {
    }
  GeometricProperties_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , bounding_box(_alloc)  {
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::semantic_knowledgebase::BoundingBox_<ContainerAllocator>  _bounding_box_type;
  _bounding_box_type bounding_box;




  typedef boost::shared_ptr< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct GeometricProperties_

typedef ::semantic_knowledgebase::GeometricProperties_<std::allocator<void> > GeometricProperties;

typedef boost::shared_ptr< ::semantic_knowledgebase::GeometricProperties > GeometricPropertiesPtr;
typedef boost::shared_ptr< ::semantic_knowledgebase::GeometricProperties const> GeometricPropertiesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace semantic_knowledgebase

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'semantic_knowledgebase': ['/home/brsu/catkin_ws/src/ensta_hbrs/semantic_knowledgebase/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbdc6669616d25728b1b59368c6443e2";
  }

  static const char* value(const ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbdc6669616d2572ULL;
  static const uint64_t static_value2 = 0x8b1b59368c6443e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "semantic_knowledgebase/GeometricProperties";
  }

  static const char* value(const ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n\
BoundingBox bounding_box\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: semantic_knowledgebase/BoundingBox\n\
geometry_msgs/Vector3[] vertices\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.bounding_box);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GeometricProperties_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::semantic_knowledgebase::GeometricProperties_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "bounding_box: ";
    s << std::endl;
    Printer< ::semantic_knowledgebase::BoundingBox_<ContainerAllocator> >::stream(s, indent + "  ", v.bounding_box);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEMANTIC_KNOWLEDGEBASE_MESSAGE_GEOMETRICPROPERTIES_H
