/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/brsu/catkin_ws/src/ensta_hbrs/semantic_knowledgebase/srv/KBService.srv
 *
 */


#ifndef SEMANTIC_KNOWLEDGEBASE_MESSAGE_KBSERVICEREQUEST_H
#define SEMANTIC_KNOWLEDGEBASE_MESSAGE_KBSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace semantic_knowledgebase
{
template <class ContainerAllocator>
struct KBServiceRequest_
{
  typedef KBServiceRequest_<ContainerAllocator> Type;

  KBServiceRequest_()
    : object_category_request()  {
    }
  KBServiceRequest_(const ContainerAllocator& _alloc)
    : object_category_request(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_category_request_type;
  _object_category_request_type object_category_request;




  typedef boost::shared_ptr< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct KBServiceRequest_

typedef ::semantic_knowledgebase::KBServiceRequest_<std::allocator<void> > KBServiceRequest;

typedef boost::shared_ptr< ::semantic_knowledgebase::KBServiceRequest > KBServiceRequestPtr;
typedef boost::shared_ptr< ::semantic_knowledgebase::KBServiceRequest const> KBServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace semantic_knowledgebase

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'semantic_knowledgebase': ['/home/brsu/catkin_ws/src/ensta_hbrs/semantic_knowledgebase/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b76fc5bfeb3d8654d3f087afc92dbec3";
  }

  static const char* value(const ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb76fc5bfeb3d8654ULL;
  static const uint64_t static_value2 = 0xd3f087afc92dbec3ULL;
};

template<class ContainerAllocator>
struct DataType< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "semantic_knowledgebase/KBServiceRequest";
  }

  static const char* value(const ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_category_request\n\
\n\
";
  }

  static const char* value(const ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_category_request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct KBServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::semantic_knowledgebase::KBServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_category_request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_category_request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEMANTIC_KNOWLEDGEBASE_MESSAGE_KBSERVICEREQUEST_H
